### ISSUE TITLE
[서버 - API]  회원가입 기능 구현

### ISSUE THREAD

**Issue by nexusz99** [nexusz99/EZStorage#5]
회원가입 폼을 받아서 데이터베이스에 저장할 수 있도록 하는 기능을 구현한다.

데이터베이스에 저장하는 부분은 #6 에서 처리한다.

**Comment by lyncia** [comment]
https://gist.github.com/lyncia/b44793bbe83d0843c6dc
https://gist.github.com/lyncia/ce07bd403cb7d7cdfef7

study and practice complete

**Comment by lyncia** [comment]
실제 사용할 DB와 연동하여 예외처리까지 모두 구현 완료
commit 완료
