### ISSUE TITLE
[서버-api] 로그인/로그아웃 api 구현

### ISSUE THREAD

**Issue by nexusz99** [nexusz99/EZStorage#9]
로그인/로그아웃 api를 구현한다.

* 세션관리 기능이 들어가야한다.

**Comment by lyncia** [comment]
로그인/로그아웃 기능 구현 및 커밋 완료
(세션키를 이용하여 로그아웃 기능을 구현하였으며 
세션키를 이용하여 다중로그인이 정상작동되도록 구현)
